### ISSUE TITLE
BLAZE to FLAMES

### ISSUE THREAD

**Issue by m-noonan** [shimlab/BLAZE#11]
Can someone provide a tutorial on how to input the BLAZE output into FLAMES? Thanks!

**Comment by parsboy66** [comment]
Thanks for providing a nice tool for BC identification, i also have this question and will be happy to know how we can trim the reads after finding putative barcodes by BLAZE and use it i flames. 

Thanks

**Comment by parsboy66** [comment]
> Can someone provide a tutorial on how to input the BLAZE output into FLAMES? Thanks!

explained here!
https://github.com/youyupei/bc_whitelist_analysis/tree/main

basically as far as i understand, BLAZE prepares a list of the putative barcodes for flames based on the identification of the short read adopter and validates it by finding poly A(T) and base call qualiy to have at least 95% acc.   however in BLAZE edit distance 2 used to match the barcodes with the whitelist of 10x , but i found it sometime edit distance more than 1 is problematic and makes 2 different barcodes (as i checked it by output of 10x) get corrected and become identical. 

i will be happy to get the comment about my understanding on BLAZE pipeline and the problem i mentioned from Authors. 


Regards
Iman

**Comment by youyupei** [comment]
Hi @m-noonan, 

Thanks for being interested in BLAZE. Currently, BLAZE outputs a barcode list (by default `whitelist.csv`) that lists all the cell-associated barcode sequences. This file can be used as input into FLAMES (https://github.com/OliverVoogd/FLAMES).  Here is an example:
```
library(FLAMES)

####Inputs that change depending on samples
###whitelists
Whitelist = "whitelist.csv"

#####fastq_files 
fastq = "path_to_fastq"

###out_dirs
output = "path_to_output_dir"

####Inputs that don't change
####referecne files 
GTF = "gencode.v31.annotation.gtf"
genome = "hg38.fa"
minimap2_dir="path_to_minimap"

# Run FLAMES
sce <- sc_long_pipeline(fastq=fastq, outdir=output, reference_csv=Whitelist, annot=GTF, genome_fa=genome, match_barcode=TRUE, MAX_DIST=2, has_UMI=TRUE, minimap2_dir=minimap2_dir)
```
Note: there are different github repo for FLAMES and the one above is the bioconductor version and it is also more actively maintianed.

Also note that we are currently in the process of simplifying the integration between BLAZE and FLAMES. We are working on a new version of BLAZE that offers improved runtime and enhanced functionalities. This updated version will be seamlessly integrated into FLAMES, eliminating the need for manual execution of BLAZE and FLAMES separately. We will provide updates on this development in a subsequent post once it is ready.


Hi @parsboy66,

Thank you for your comments; your understanding is mostly correct. I'd like to clarify a minor point: if you are using the BLAZE tool in the main branch of this repository, the putative barcodes are solely utilized to generate the barcode list. At this stage, there is no involvement of edit distance. The barcode list is summarised from a pool of high-quality putative barcodes, with the aim of identifying true barcode sequence for each cell.

Subsequently, in the current implementation, FLAMES comes into play by assisting in assigning reads to each barcode (i.e., cell), allowing for a certain level of edit distance.

Regarding the issue you mentioned, I may need more information to answer it effectively. If you have reads from two different barcodes, but only one of them is listed in the `whitelist.csv`, the cause may not be related to edit distance but rather insufficient high-quality reads associated with the missing barcode. When discussing read-to-cell assignment, it's likely that some reads may have been misassigned if the allowed edit distance is increased.

I'm open to further discussion and would be happy to delve deeper into this matter.

Yupei

**Comment by parsboy66** [comment]
Dear Yupei

Thank you for the nice comments and for replying ASAP.

Actually, I have been using FLAMES for a long time, and one of the things i realized before applying it, was to selecting high quality cells by analyzing 10x data (BLAZE helped us to get rid of this part) and then applying the Levenshtein method on the list of the barcodes to find the best edit distance number in order to not allowing two different barcodes become identical after correction. well, I think this part can be implemented in BLAZE to check the whitelist.csv and suggest to the users the best edit distance that can be used in FLAMES.


Regards
Iman

**Comment by m-noonan** [comment]
Thank you @youyupei, this is very helpful! Is there a way to incorporate the "combined_isoform_plot" using BLAZE --> FLAMES? It's a very appealing visualization that I would like to use. Would you be able to provide an example of how to create those plots for running FLAMES with BLAZE as input? Thank you!

**Comment by youyupei** [comment]
Hi @m-noonan, 

You may create a Seurat object using the count matrix output by FLAMES, so that many plotting functions in Seurat can be used. here is the code of how we generated different plots when we were doing the analysis:
```
plot_umap <- function(count.matrix, min.features = 200,max.feature = 999999999, npc = 5, cluster_res = 0.7, fig_name = ''){

  # init 
  rst_figures <- list()
  rst_table = data.frame()

    counts <- read.csv(count.matrix)
    
    seurat_object <- CreateSeuratObject(counts = counts, project = "singlecell", min.cells = 3, min.features = 0.5)
    rst_table <- rbind(rst_table, data.frame("Cells"=dim(seurat_object)[2],
                                             "median feature per Cell"=median(seurat_object$nFeature_RNA), row.names = paste0('min features > 0'),check.names = FALSE))
    
    #remove unwanted cells. below are default settings but you can modify these
    seurat_object <- subset(seurat_object, subset = nFeature_RNA > min.features & nFeature_RNA < max.feature) 
        rst_table <- rbind(rst_table, data.frame("Cells"=dim(seurat_object)[2],
                                             "median feature per Cell"=median(seurat_object$nFeature_RNA), row.names = paste0('min features > 0', min.features),check.names = FALSE))
    
    #now you have removed unwanted cells, it is time to normalize the data. By default, Seurat employs a global-scaling normalization method "LogNormalize" that normalizes the feature expression measurements for each cell by the total expression, multiplies this by a scale factor (10,000 by default), and log-transforms the result.
    seurat_object <- NormalizeData(seurat_object, normalization.method = "LogNormalize", scale.factor = 10000)
    #you can alternatively input seurat_object <- NormalizeData(seurat_object) instead of above.
    #we now identify highly variable features in order to determine a subset of features that exhibit high cell-to-cell 
    
    #variation in the dataset.
    seurat_object <- FindVariableFeatures(seurat_object, selection.method = "vst", nfeatures = 2000)
    
    #now we apply a linear transformation (scaling) that is a standard pre-processing step prior to dimensional reduction techniques like PCA
    all.genes <- rownames(seurat_object)
    seurat_object <- ScaleData(seurat_object, features = all.genes)
    #we can visualise both cells and features that define the PCA
    seurat_object <- RunPCA(seurat_object, features = VariableFeatures(object = seurat_object))
    #this can be visualised using an Elbow Plot
    #rst_figures <- append(rst_figures, ElbowPlot(seurat_object))
    
    #to cluster cells, I have used the number of sig. PCs that I observed in the above plots. The findneighbors function is for constuction of a KNN graph based on euclidean distance in PCA space and refines edge weights between any two cells based on the shared overlap in their local neighborhoods (jaccard similarity). It uses the input of previously defined dimensionality of the dataset.
    seurat_object <- FindNeighbors(seurat_object, dims = 1:npc)
    #now to actually cluster the cells, we apply modularity optimisation techniques (default is Louvain algorithm). The findclusters function contains a resolution parameter which sets the granularity of downstream clustering. Settings are recommended between 0.4-1.2, but may need to be increased for larger datasets.
    seurat_object <- FindClusters(seurat_object, resolution = cluster_res)
    
    #to View metadata
    #seurat_object@meta.data
    #run non-linear dimensional reduction (UMAP/tSNE)
    seurat_object <- RunUMAP(seurat_object, dims = 1:npc)
    
    rst_figures <- append(rst_figures, list(DimPlot(seurat_object, reduction = "umap") + labs(color = "cluster \n(from PCA)", title = '') + theme(text = element_text(size = 10))  )) 
    
    
    rst_figures <- append(rst_figures, list(
      FeaturePlot(seurat_object, reduction = "umap", features = 'nCount_RNA')+labs(color = "UMI count",title = '')+ theme(text = element_text(size = 10)),
    FeaturePlot(seurat_object, reduction = "umap", features = 'nFeature_RNA')+labs(color = str_wrap("Feature count (isoform/gene)",15),title = '')+ theme(text = element_text(size = 10))
    ))
    
    
    plot_pc <- ElbowPlot(seurat_object)+labs(title = 'SD explained by each PC') + theme(text = element_text(size = 10))
    plot_umap <- grid.arrange(plot_pc, tableGrob(rst_table), rst_figures[[1]], rst_figures[[2]], rst_figures[[3]], ncol=2, top=textGrob(fig_name))
    list(plot_umap, seurat_object)
}
```
