### ISSUE TITLE
Fastq size drops after Blaze

### ISSUE THREAD

**Issue by rania-o** [shimlab/BLAZE#15]
Hi developpers,

I used blaze on nanopore data. My initial fastq size was ~150G per sample.
After using blaze, my fastq size dropped to ~70G per sample.
In summary, only 7% of reads failed. 
Is it normal to observe such a decrease in the size of the fastq?

Thanks,
Rania

**Comment by youyupei** [comment]
Hi @rania-o ,

Thanks for being interested in BLAZE. Usually, I got ~70% of reads left in the final fastq file however the proportion did vary across samples and experiments. I would NOT say that there is definitely something wrong in your run. But it's good to double-check:

* Did the data come from 10X 3' (v3) protocol, or any custumisation involved?
* Does the "knee plot" output by BLAZE look abnormal?

Regards,
Yupei

**Comment by rania-o** [comment]
Hi @youyupei 

Thanks for your fast reply, I was waiting for the answer of biologists regarding the protocol they used. Indeed, it's the v3 one.
I put here some knee plots from my samples, they look normal (I don't have much experience in single cell analysis) :

![Screenshot from 2024-04-05 11-52-57](https://github.com/shimlab/BLAZE/assets/102246981/85c39477-ea61-4c9e-bf62-83aa20afa0b7)

![Screenshot from 2024-04-05 11-53-26](https://github.com/shimlab/BLAZE/assets/102246981/1effdf6d-9dc6-4ac7-be92-218bd872cb6f)

![Screenshot from 2024-04-05 11-53-50](https://github.com/shimlab/BLAZE/assets/102246981/5bef0c44-b5f2-4647-987a-af29d7164f85)

Rania

**Comment by youyupei** [comment]
Hi @rania-o, The knee plot looks okay to me. Did you proceed to the downstream analysis with the fastq file generated? Hope it is still fine for getting useful result.

**Comment by sparthib** [comment]
Hi @youyupei , I am getting similar results where across my samples on average only 35% of the reads are matched. My knee plots look similar too. What could be the reasons for this? I made sure I'm using the right adapter sequences. Thanks.

**Comment by youyupei** [comment]
Hi @sparthib ,

Would you be able to share what was written in the summary file?

**Comment by sparthib** [comment]
hi @youyupei here it is:

```
Total number of reads: 
            44,314,904
        Reads with unambiguous polyT and adapter positions found:            
            21,885,902 (49.39% of all reads)
            5,303,893 in which all bases in the putative BC have Q>=15
        Failed Reads: 
            no polyT and adapter positions found: 
                20,658,911 (46.62% of all reads)
            polyT and adapter positions found in both end (fail to determine strand): 
                1,411,151 (3.18% of all reads)
            multiple polyT and adapter found in one end
                358,940 (0.81% of all reads)
```

Thanks!
Sowmya

**Comment by rania-o** [comment]
Hello @youyupei,

Thanks for your reply, and yes I continued my analysis but the number of cells was less than expected.
Here is the summary file for one of my samples (they all look good) :
```
Total number of reads: 
            124,405,398
        Reads with unambiguous polyT and adapter positions found:            
            115,391,482 (92.75% of all reads)
            50,720,848 in which all bases in the putative BC have Q>=15
        Failed Reads: 
            no polyT and adapter positions found: 
                5,446,625 (4.38% of all reads)
            polyT and adapter positions found in both end (fail to determine strand): 
                1,714,413 (1.38% of all reads)
            multiple polyT and adapter found in one end
                1,852,878 (1.49% of all reads)
```

Rania

**Comment by youyupei** [comment]
Hi @sparthib , the main problem was 46.6% of reads where polyT or adaptor sequence can not be identified in the reads so  the barcode can't be located. Not sure why it happens, it can be that many reads are truncated during the sequencing or have the data been trimmed by any upstream tools? 

@rania-o both your summary file and knee plot look fine. From the knee plots, I think BLAZE did include most of well-sequenced cells.  If you really want to keep more cells, you could turn on the `--high-sensitivity-mode`, but please note that this could include more false positive cells and requires more careful QC during the analysis.

**Comment by sparthib** [comment]
Thanks @youyupei, it gives a similar summary with raw fastq files wherein a high number of reads where polyT or adapter sequence is unidentified, I will look further into whether there was a lot of  truncation during sequencing.

**Comment by sparthib** [comment]
Hi @youyupei , just for clarity, the adaptor used to identify the UMI and barcode is the forward primer on the 5' end (and not the TSO), is that right?
