### ISSUE TITLE
Cannot save file into a non-existent directory

### ISSUE THREAD

**Issue by nick-youngblut** [shimlab/BLAZE#16]
If the output directory does not exist, blaze throws the error: `OSError: Cannot save file into a non-existent directory:`. Assuming that the user knows what they are doing ("we're all adults here"), then the user's intent is for the software to create the directory instead of throwing an error and forcing the user to manually create the directory path. So, it would be great to have an `os.makedirs()` in blaze instead of the `OSError`.

**Comment by youyupei** [comment]
Hi @nick-youngblut, 

Thanks for the good suggestion. It will be added (I will leave this open until then).  

Regards,
Yupei
