### ISSUE TITLE
Error in running blaze

### ISSUE THREAD

**Issue by lingminhao** [shimlab/BLAZE#2]
Hi @heejungshim, @youyupei  , I tried running blaze on my dataset using ` time python3 blaze.py --expect-cells=1500 --threads=8 ./data/` and I get this error: 

![image](https://user-images.githubusercontent.com/53725270/204675793-6338916c-f53e-4c30-be33-21d63d8c7843.png)

What is the problem?

**Comment by youyupei** [comment]
Hi @lingminhao,

Thanks for being interested in this tool. Would you be able to let me know if it ran successfully on the test run or not (https://github.com/shimlab/BLAZE#test-run)?

**Comment by lingminhao** [comment]
Hi @youyupei , it works using test-run and I solved this by renaming the file extension to fastq and now everything works !
