### ISSUE TITLE
putative barcode list minQ column bug

### ISSUE THREAD

**Issue by lingminhao** [shimlab/BLAZE#3]
Hi @youyupei  , I successfully ran the blaze and get the output but I realized that the minQ column had some barcodes with phred score lower than 15 even I ran blaze in default mode (should be >=15?)

**Comment by youyupei** [comment]
Hi @lingminhao, sorry for the confusion, we will improve the document to make this clearer. The program should output two CSV files. The minQ threshold only affects the whitelist (`whitelist.csv`). 

For `putative_bc.csv`,  we output putative barcodes for all reads when possible; no filtering is applied in this file. We believe that having all of the putative barcodes is useful, especially when you wanted to reduce the minQ threshold and re-generate the whitelist.

**Comment by lingminhao** [comment]
Hi @youyupei thanks for the clarification ! Just last thing to ask before I close this issue, is the total sum of a specific barcodes means all the reads that has exact barcodes found? How about the rest of the reads with edit distance >=1 , are they included or I have to run other downstream analysis tools like FLAMES for the assignment?

**Comment by youyupei** [comment]
Hi @lingminhao, the short answer is: you need to run other downstream tools like FLAMES. 

A putative barcode (in the `putative_bc.csv` file) is a subsequence of each read that corresponds to the barcode region. There could still be basecalling errors inside. Although people may do the assignment by matching the putative barcodes to the whitelist in BLAZE output (e.g. use edit distance ). We didn't implement it since tools like FLAMES will perform this step anyway.

**Comment by lingminhao** [comment]
Hi @youyupei , I think I get it now, but just let me reiterate to double confirm the process of blaze. 
1) find putative barcode by the use of read 1 adapter and poly(dT). Those reads that fails to locate read 1 adapter and poly(dT) are not considered. These putative barcode are recorded in `putative_bc.csv` with their respective minQ. Reads that fails to locate read 1 adapter and poly(dT) are listed without the barcodes / minQ. 

2) Choose the putative barcode that exactly matches the 10x Genomics whitelist. From these putative barcode, filter out the ones with minQ >= 15 and read count threshold based on expected number of cells. The barcodes that passed all these criterions are recorded in the `whitelist.csv`. 

Am I right?

**Comment by youyupei** [comment]
Hi @lingminhao, you get it exactly right!
