### ISSUE TITLE
Considerations for UMI correction

### ISSUE THREAD

**Issue by lingminhao** [shimlab/BLAZE#4]
Hi @youyupei , I just had a question on whether there will be plans for this tool to support UMI correction as well?

**Comment by youyupei** [comment]
Hi @lingminhao,  thanks for being interested in our work. As you might be aware that tools like FLAMES perform UMI clustering already. We find the UMI clustering method proposed in FLAMES is reasonable, so in the current version of BLAZE, we didn’t seek to replicate the function. However, formal performance assessment of UMI method in FLAMES is not available. So, there is still a possibility that we will consider developing a new UMI calling methods in the future if we find the performance of the current available methods is not satisfying. Feel free to email me for more discussion about this topic.
