### ISSUE TITLE
about guppy

### ISSUE THREAD

**Issue by junhaiqi** [shimlab/BLAZE#8]
Hi @youyupei , I've read about the work on blaze and would like to try to compare with guppy, however at the moment I'm having trouble getting the latest version of guppy. Can you help me download the latest version of guppy? Thank you very much!

**Comment by youyupei** [comment]
Hi @junhaiqi, thanks for being interested in BLAZE. To download and run Guppy, I recommend visiting the Nanopore community website at https://nanoporetech.com/community. You will find a wealth of helpful resources there.
