### ISSUE TITLE
Conda or other Containers availablility

### ISSUE THREAD

**Issue by atrull314** [shimlab/BLAZE#9]
Hi,

Thank you for building this tool. I was wondering if there were any pre-built conda environments or containers (docker/singularity) available for this tool?

Thanks!

**Comment by youyupei** [comment]
Hi @atrull314,

Thanks for being interested in BLAZE. There isn't currently a pre-built container. But you could set up a conda environment using the configure file provided. You could find the details here: https://github.com/shimlab/BLAZE#conda-environment.

Regards
Yupei

**Comment by nick-youngblut** [comment]
Maybe it would be best to open this issue back up until a bioconda recipe is created by someone? Otherwise, you might get this issue reposted many times.
